# -*- coding: utf-8 -*-
"""LinguaFlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEAhBcJYHCvKp1LEuJMBR4iHpuURiMon
"""

!pip install flask-ngrok deep-translator

!pip install pyngrok

# 1. Install library (jika belum)
#!pip install flask pyngrok deep-translator

from flask import Flask, request, jsonify
from pyngrok import ngrok
from deep_translator import GoogleTranslator

app = Flask(__name__)

# --- BAGIAN KEAMANAN: Ganti dengan Token Anda sendiri ---
# Jangan bagikan token asli Anda di internet atau GitHub
NGROK_TOKEN = "YOUR_NGROK_AUTH_TOKEN_HERE"
ngrok.set_auth_token(NGROK_TOKEN)

try:
    # Menggunakan koneksi standar tanpa hostname statis agar bisa digunakan siapa saja
    public_url = ngrok.connect(5000).public_url
except Exception as e:
    print(f"Error connecting to ngrok: {e}")
    public_url = "URL_NOT_FOUND"

print(f"✅ SERVER AKTIF DENGAN PILIHAN BAHASA")
print(f"🔗 URL: {public_url}/translate")
print(f"----------------------------------------------------------")
print("KODE BAHASA POPULER:")
print("Indonesia: id | Cina: zh-CN | Jepang: ja | Arab: ar | Korea: ko | Filipina: tl")
print("Rusia: ru | Inggris: en | Prancis: fr | Spanyol: es | Portugal: pt | Italia: it")
print("----------------------------------------------------------")

@app.route('/translate', methods=['GET'])
def translate_text():
    text = request.args.get('text')
    dest_lang = request.args.get('dest', 'id')

    if not text:
        return jsonify({"error": "No text provided"}), 400

    try:
        translated = GoogleTranslator(source='auto', target=dest_lang).translate(text)
        return jsonify({
            "original": text,
            "translated": translated,
            "dest_lang": dest_lang
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run()

from pyngrok import ngrok
ngrok.kill()